project:
  type: website

website:
  title: "{targets} workshop"
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - typical_R_projects.qmd
      - pure_functions.qmd
      - targets_plan.qmd
      - debugging.qmd
      - branching.qmd
      - long_vs_wide.qmd
      - getting_help.qmd
      - more.qmd

